"""add multi-day and approximate time to events

Revision ID: 08a8e54e605a
Revises: ab338fdcd6fa
Create Date: 2026-07-07 19:47:44.489268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a8e54e605a'
down_revision: Union[str, Sequence[str], None] = 'ab338fdcd6fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('time_is_approximate', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('approximate_period', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'approximate_period')
    op.drop_column('events', 'time_is_approximate')
    op.drop_column('events', 'end_date')
    # ### end Alembic commands ###
