"""baseline - initial schema

Revision ID: 420772ac2ffe
Revises: 
Create Date: 2026-07-07 13:17:24.410908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '420772ac2ffe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_messages_created_at'), 'contact_messages', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('bike_model', sa.String(), nullable=True),
    sa.Column('home_region', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('accepted_disclaimer_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('stories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('ADVENTURE', 'FOUR_STROKE', 'TWO_STROKE', 'DUAL_SPORT', 'OTHER', name='vehicletype'), nullable=False),
    sa.Column('vehicle_type_other', sa.String(), nullable=True),
    sa.Column('ride_style', sa.Enum('SCENIC_TOURING', 'FAST_RALLY', 'TECHNICAL_SINGLES', 'HARD_ENDURO_EXTREME', name='ridestyle'), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MODERATE', 'HARD', 'EXTREME', name='difficulty'), nullable=False),
    sa.Column('season', sa.Enum('WINTER', 'SUMMER', 'ALL_YEAR', name='season'), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('meeting_point_label', sa.String(), nullable=True),
    sa.Column('meeting_point_lat', sa.Float(), nullable=True),
    sa.Column('meeting_point_lon', sa.Float(), nullable=True),
    sa.Column('parking_security', sa.Enum('SAFE', 'RISK', name='parkingsecurity'), nullable=True),
    sa.Column('gpx_url', sa.String(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('elevation_profile_json', sa.Text(), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=True),
    sa.Column('start_lon', sa.Float(), nullable=True),
    sa.Column('cover_photo_url', sa.String(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_country'), 'stories', ['country'], unique=False)
    op.create_index(op.f('ix_stories_created_at'), 'stories', ['created_at'], unique=False)
    op.create_index(op.f('ix_stories_difficulty'), 'stories', ['difficulty'], unique=False)
    op.create_index(op.f('ix_stories_is_published'), 'stories', ['is_published'], unique=False)
    op.create_index(op.f('ix_stories_region'), 'stories', ['region'], unique=False)
    op.create_index(op.f('ix_stories_ride_style'), 'stories', ['ride_style'], unique=False)
    op.create_index(op.f('ix_stories_season'), 'stories', ['season'], unique=False)
    op.create_index(op.f('ix_stories_vehicle_type'), 'stories', ['vehicle_type'], unique=False)
    op.create_table('user_bikes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bikes_user_id'), 'user_bikes', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_story_id'), 'comments', ['story_id'], unique=False)
    op.create_table('likes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_likes_story_id'), 'likes', ['story_id'], unique=False)
    op.create_index(op.f('ix_likes_user_id'), 'likes', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('COMMENT', 'TRAIL_UPDATE', 'LIKE', name='notificationtype'), nullable=False),
    sa.Column('story_id', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('story_photos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trail_updates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'BLOCKED', 'MUDDY', 'UNKNOWN', name='trailstatus'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trail_updates_created_at'), 'trail_updates', ['created_at'], unique=False)
    op.create_index(op.f('ix_trail_updates_story_id'), 'trail_updates', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trail_updates_story_id'), table_name='trail_updates')
    op.drop_index(op.f('ix_trail_updates_created_at'), table_name='trail_updates')
    op.drop_table('trail_updates')
    op.drop_table('story_photos')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_likes_user_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_story_id'), table_name='likes')
    op.drop_table('likes')
    op.drop_index(op.f('ix_comments_story_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_user_bikes_user_id'), table_name='user_bikes')
    op.drop_table('user_bikes')
    op.drop_index(op.f('ix_stories_vehicle_type'), table_name='stories')
    op.drop_index(op.f('ix_stories_season'), table_name='stories')
    op.drop_index(op.f('ix_stories_ride_style'), table_name='stories')
    op.drop_index(op.f('ix_stories_region'), table_name='stories')
    op.drop_index(op.f('ix_stories_is_published'), table_name='stories')
    op.drop_index(op.f('ix_stories_difficulty'), table_name='stories')
    op.drop_index(op.f('ix_stories_created_at'), table_name='stories')
    op.drop_index(op.f('ix_stories_country'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_contact_messages_created_at'), table_name='contact_messages')
    op.drop_table('contact_messages')
    # ### end Alembic commands ###
