"""add username, motocross, desert dunes ride style

Revision ID: 48a37bec2497
Revises: 420772ac2ffe
Create Date: 2026-07-07 18:12:25.752719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48a37bec2497'
down_revision: Union[str, Sequence[str], None] = '420772ac2ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###

    # הרחבת ה-enum types הקיימים בפועל - autogenerate לא תופס שינויי ערכים ב-enum,
    # וב-Postgres צריך ALTER TYPE מפורש (ורץ מחוץ לטרנזקציה, לכן autocommit_block)
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE vehicletype ADD VALUE IF NOT EXISTS 'MOTOCROSS'")
            op.execute("ALTER TYPE ridestyle ADD VALUE IF NOT EXISTS 'DESERT_DUNES'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
    # הערה: Postgres לא תומך בהסרת ערך מ-enum type בפשטות - אם אי פעם צריך downgrade
    # אמיתי כאן, זה דורש בניית טיפוס חדש והעברת הנתונים. לא ממומש בכוונה.
