"""add events and event rsvps

Revision ID: 5b9e313c5a07
Revises: 48a37bec2497
Create Date: 2026-07-07 18:23:48.460260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b9e313c5a07'
down_revision: Union[str, Sequence[str], None] = '48a37bec2497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organizer_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('ADVENTURE', 'FOUR_STROKE', 'TWO_STROKE', 'DUAL_SPORT', 'MOTOCROSS', 'OTHER', name='vehicletype'), nullable=True),
    sa.Column('difficulty', sa.Enum('EASY', 'MODERATE', 'HARD', 'EXTREME', name='difficulty'), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('meeting_point_label', sa.String(), nullable=True),
    sa.Column('meeting_point_lat', sa.Float(), nullable=True),
    sa.Column('meeting_point_lon', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_organizer_id'), 'events', ['organizer_id'], unique=False)
    op.create_table('event_rsvps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_rsvps_event_id'), 'event_rsvps', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_rsvps_user_id'), 'event_rsvps', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # הרחבת enum קיים - autogenerate לא תופס שינויי ערכים בעמודה קיימת
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'EVENT_RSVP'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_rsvps_user_id'), table_name='event_rsvps')
    op.drop_index(op.f('ix_event_rsvps_event_id'), table_name='event_rsvps')
    op.drop_table('event_rsvps')
    op.drop_index(op.f('ix_events_organizer_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
