"""add events and event rsvps

Revision ID: 5b9e313c5a07
Revises: 48a37bec2497
Create Date: 2026-07-07 18:23:48.460260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b9e313c5a07'
down_revision: Union[str, Sequence[str], None] = '48a37bec2497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    is_postgres = bind.dialect.name == "postgresql"

    # טבלת events - בלי שתי עמודות ה-enum (vehicle_type, difficulty) בשלב הזה.
    # הן משתמשות ב-enum types שכבר קיימים מהמיגרציית בייסליין, ו-SQLAlchemy
    # מנסה ליצור אותם מחדש גם עם create_type=False (זו תקלה מוכרת ב-Alembic:
    # https://github.com/sqlalchemy/alembic/issues/1347) - אז מוסיפים אותן
    # למטה עם SQL גולמי שרק מצביע על הטיפוס הקיים, בלי לגעת ב-DDL האוטומטי.
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organizer_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('meeting_point_label', sa.String(), nullable=True),
    sa.Column('meeting_point_lat', sa.Float(), nullable=True),
    sa.Column('meeting_point_lon', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_organizer_id'), 'events', ['organizer_id'], unique=False)

    if is_postgres:
        op.execute("ALTER TABLE events ADD COLUMN vehicle_type vehicletype")
        op.execute("ALTER TABLE events ADD COLUMN difficulty difficulty")
    else:
        # SQLite (רק לבדיקות מקומיות) - אין enum אמיתי, עמודת טקסט רגילה מספיקה
        op.add_column('events', sa.Column('vehicle_type', sa.String(), nullable=True))
        op.add_column('events', sa.Column('difficulty', sa.String(), nullable=True))

    op.create_table('event_rsvps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_rsvps_event_id'), 'event_rsvps', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_rsvps_user_id'), 'event_rsvps', ['user_id'], unique=False)

    # הרחבת enum קיים - autogenerate לא תופס שינויי ערכים בעמודה קיימת
    if is_postgres:
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'EVENT_RSVP'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_rsvps_user_id'), table_name='event_rsvps')
    op.drop_index(op.f('ix_event_rsvps_event_id'), table_name='event_rsvps')
    op.drop_table('event_rsvps')
    op.drop_index(op.f('ix_events_organizer_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
