"""add email verification fields

Revision ID: 79ecea4cfbe8
Revises: 83b6bf548f76
Create Date: 2026-07-07 21:12:57.421017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ecea4cfbe8'
down_revision: Union[str, Sequence[str], None] = '83b6bf548f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_verify_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_verify_token_expires', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_email_verify_token'), 'users', ['email_verify_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_verify_token'), table_name='users')
    op.drop_column('users', 'email_verify_token_expires')
    op.drop_column('users', 'email_verify_token')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
